Add option to override final EOL in file
jprichardson/node-jsonfile pull request #137
Opened 2020-10-17 14:33 UTC by asingh04

Added a check for an option `finalEOL`. 
If the `finalEOL` is absent in the `options` object, the EOL(`\n`) character will be appended at end of file while writing, in order to maintain backward compatibility.

If the `finalEOL` option has any falsey value, the EOL at the end of the file will be not be written.

2020-10-17 14:56 UTC, RyanZim requested changes
No point testing for truthy values other than `true`.

Also, this will need docs.

We also should probably use destructuring with default parameters in `stringify` to simplify the logic.

2020-10-17 14:56 UTC, RyanZim commented on test/write-file-sync.test.js
> +      jf.writeFileSync(file, obj, { finalEOL: [] })
```suggestion
      jf.writeFileSync(file, obj, { finalEOL: true })
```

2020-10-17 14:56 UTC, RyanZim commented on test/write-file.test.js
> +      jf.writeFile(file, obj, { finalEOL: [] }, (err) => {
```suggestion
      jf.writeFile(file, obj, { finalEOL: true }, (err) => {
```

2020-10-18 12:34 UTC, asingh04 commented on test/write-file-sync.test.js
> +      jf.writeFileSync(file, obj, { finalEOL: [] })
changes done

2020-10-18 12:34 UTC, asingh04 commented on test/write-file.test.js
> +      jf.writeFile(file, obj, { finalEOL: [] }, (err) => {
changes done

2020-10-18 12:36 UTC, asingh04 commented
1. Changes done in the test files
2. Used object destructuring in the `stringify` function of `utils` file
3. Updated the `README` file

2020-10-19 13:52 UTC, RyanZim approved these changes
LGTM

2020-10-31 14:57 UTC, merged